const data ={
    products: [
        {
            name: 'Backwood barbie',
            slug: 'Backwood-barbie',
            category: 'T-shirt',
            image: '/images/p1..jpg',
            price: 30,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 10, 
            description: 'high quality design on high quality fabric blah blah blah',
        },
        {
            name: 'Will Smith 90s Flashback',
            slug: 'will-smith-90s-flashback',
            category: 'Hoodie',
            image: '/images/p1..jpg',
            price: 30,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10, 
            description: 'high quality design on high quality fabric blah blah blah',
        }, {
            name: 'Pretty Black & Dope',
            slug: 'pretty-black-&-dope',
            category: 'Hoodie',
            image: '/images/p1..jpg',
            price: 30,
            countInStock: 10,
            brand: 'Nike',
            rating: 3.8,
            numReviews: 10, 
            description: 'high quality design on high quality fabric blah blah blah',
        },
    ],
};
